### ISSUE TITLE
Migrere innloggingsstatus til GCP

### ISSUE THREAD

**Issue by ojnybo** [navikt/innloggingsstatus#14]

**Comment by tronghn** [comment]
Denne er nå flyttet til GCP.

Noen notater:

- Sensu er deprecated og finnes ikke i GCP, så metrikker kan ikke lenger pushes hit. I GCP har vi bare satt hosten for denne til `""` slik at funksjonaliteten er stubbet ut.
- AppDynamics er ikke tilgjengelig fra GCP, så den er også fjernet fra Dockerfilen.
- Bruker fremdeles servicebruker og API-GW til å snakke med `security-token-service` og `pdl-api`. Ideelt sett burde man bare brukt TokenX mot `pdl-api` direkte (dog blir det noe problematisk med å bytte self-issued tokens inn mot TokenX). Evt. kan man bruke Azure AD for maskin-til-maskin kall.
- OpenAM er også utilgjengelig fra GCP, men den er jo også skrudd av nå, så her kan man også fjerne en del død kode.
- Secretene som tidligere lå i Vault ligger nå som en Kubernetes secret kalt `innloggingsstatus-env`.
